### ISSUE TITLE
navbar not showing up after installation

### ISSUE THREAD

**Issue by cramjaco** [shoval/jupyter-navbar#2]
I seem to be having some trouble getting the navbar to show up in my jupyter notebooks. I installed exactly (I think) as described under the Manual Installation section.  When I run jupyter notebook in linux, I get the error messages attached to the bottom of this issue. Then when I look at my notebook there appears to be no navigator. Any idea about what I might be doing wrong?

Thanks.

> $ jupyter notebook --NotebookApp.token='cow323' --no-browser --port 8899
> [I 12:20:35.210 NotebookApp] JupyterLab beta preview extension loaded from /home/jcram/Programs/anaconda3/lib/python3.6/site-packages/jupyterlab
> [I 12:20:35.210 NotebookApp] JupyterLab application directory is /home/jcram/Programs/anaconda3/share/jupyter/lab
> [I 12:20:35.226 NotebookApp] Serving notebooks from local directory: /home/jcram
> [I 12:20:35.226 NotebookApp] 0 active kernels 
> [I 12:20:35.226 NotebookApp] The Jupyter Notebook is running at: http://localhost:8899/?token=...
> [I 12:20:35.227 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 12:20:42.420 NotebookApp] 302 GET / (127.0.0.1) 1.30ms
> [W 12:20:42.666 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.css (127.0.0.1) 28.02ms referer=http://localhost:8899/custom/custom.css
> [W 12:20:42.823 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.js?_=1520022042684 (127.0.0.1) 2.68ms referer=http://localhost:8899/tree?
> [W 12:20:49.576 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.css (127.0.0.1) 4.65ms referer=http://localhost:8899/custom/custom.css
> [W 12:20:49.862 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.js?_=1520022049595 (127.0.0.1) 2.59ms referer=http://localhost:8899/tree/Programs
> [W 12:20:58.873 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.css (127.0.0.1) 3.05ms referer=http://localhost:8899/custom/custom.css
> [W 12:20:59.173 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.js?_=1520022058892 (127.0.0.1) 2.72ms referer=http://localhost:8899/tree
> [W 12:21:00.895 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.css (127.0.0.1) 2.47ms referer=http://localhost:8899/custom/custom.css
> [W 12:21:01.205 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.js?_=1520022060915 (127.0.0.1) 2.37ms referer=http://localhost:8899/tree/Projects
> [W 12:21:02.266 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.css (127.0.0.1) 2.39ms referer=http://localhost:8899/custom/custom.css
> [W 12:21:02.486 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.js?_=1520022062285 (127.0.0.1) 2.47ms referer=http://localhost:8899/tree/Projects/mubiomeCOR
> [W 12:21:04.368 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.css (127.0.0.1) 2.44ms referer=http://localhost:8899/custom/custom.css
> [W 12:21:04.736 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.js?_=1520022064386 (127.0.0.1) 2.37ms referer=http://localhost:8899/tree/Projects/mubiomeCOR/JACAnalysis
> [W 12:21:11.035 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.css (127.0.0.1) 3.01ms referer=http://localhost:8899/custom/custom.css
> [W 12:21:12.120 NotebookApp] 404 GET /custom/jupyter-navbar/navbar.js?_=1520022071273 (127.0.0.1) 2.61ms referer=http://localhost:8899/notebooks/Projects/mubiomeCOR/JACAnalysis/Feb2018_096.ipynb
> [I 12:21:17.056 NotebookApp] Kernel started: a5ee6d89-9d80-4d23-b491-8c50797955c1

**Comment by shoval** [comment]
The 404 errors suggest that the initialization code gets executed, but the files in the jupyter-navbar subdir aren't found. Could you please tell me the structure you have under the .jupyter/custom/ directory? 

Example:
```
 ~/.jupyter/custom
$ ls -l *
-rw-r--r-- 1 User 197121 45 Jan 16 09:49 custom.css
-rw-r--r-- 1 User 197121 52 Jan 16 09:49 custom.js

jupyter-navbar:
total 8
-rw-r--r-- 1 User 197121 1033 Jan 16 09:49 navbar.css
-rw-r--r-- 1 User 197121 1978 Jan 16 09:49 navbar.js
```

**Comment by cramjaco** [comment]
Ah. It appears I had set that folder up wrong. The navbar.css and navbar.js were in ~/.jupyter/custom rather than ~/jupyter/custom/jupyter-navbar.

Still having issues but I'll open a separate thread for those.
