### ISSUE TITLE
Not working as expected in Firefox

### ISSUE THREAD

**Issue by tom-wood** [shoval/jupyter-navbar#5]
Hi there,

This isn't working as expected in Mozilla Firefox on my system (Windows 10). The "sidebar" appears at the top of the page and is non-resizable/movable (but the ToC links work nicely). On trying with Internet Edge (?!) the sidebar appears as a sidebar as expected. Do you have any ideas on how to fix this kind of behaviour? I'm working with Firefox 64.0, Windows 10, python 3.6; I did the manual install as per the instructions in the Readme file.

Many thanks - it looks like an extremely useful feature.

**Comment by shoval** [comment]
Hi @tom-wood, this sounds like a CSS problem. Did you try a hard refresh (ctrl+F5)? Does this problem still persist?

**Comment by tom-wood** [comment]
Hi @shoval. Thanks for replying. Inevitably I can no longer reproduce the issue, having in the interim done a complete reinstall of anaconda. The good news is that it all works brilliantly, so I'm closing this.
