### ISSUE TITLE
not working with identical named headings

### ISSUE THREAD

**Issue by amsIntAG** [shoval/jupyter-navbar#6]
if i have a second label named identical it jumps to the first occurrence.

**Comment by shoval** [comment]
Are you sure you are running the latest version? I updated the code at the end of March to address this issue, and it seemed to have solved it (at least in the scenarios I ran). If you have this problem in the latest version, please provide a way to reproduce the problem.

**Comment by amsIntAG** [comment]
I downloaded the code today, so I have the newest version. With the attached notebook the error occurs already.

Thanks for your help.

**Comment by shoval** [comment]
@amsIntAG please attach in the thread itself, and not by email, as it doesn't seem to work.

**Comment by amsIntAG** [comment]
I attached the jupyter notebook in the zip file. 


[NavBar Test.zip](https://github.com/shoval/jupyter-navbar/files/3199428/NavBar.Test.zip)

**Comment by ederag** [comment]
It seems to work fine now:
![Screenshot_20220327_144726](https://user-images.githubusercontent.com/10962809/160282068-fbcd6d10-b25f-4f8a-90c0-bfb33a496ff9.png)
Tested with the latest dcc24fb428cc9be5d75d8e33442033a2eda1dc6e.

This navbar is awesome, thanks @shoval !
