### ISSUE TITLE
Couple of questions - resize and collapse

### ISSUE THREAD

**Issue by RabbitJackTrade** [shoval/jupyter-navbar#8]
Hi, and thanks for the navbar!

Three questions:
The tab in the middle of the main window can be clicked to hide an unhide the navbar, but I don't see a way to resize the navbar.
Similarly, I don't see a way to collapse the hierarchy in the navbar.
Finally, is there a way to selectively disable the navbar for specific notebooks? Or to generally disable it?

Thanks.

**Comment by shoval** [comment]
Hi there!

1) The resizing is performed using the [CSS "resize" property](https://www.w3schools.com/cssref/css3_pr_resize.asp), which might be browser/environment dependent. It appears this way in my browser (sorry for the dark theme):
![image](https://user-images.githubusercontent.com/1183305/96737192-0dbeea00-13c6-11eb-9c7c-042e6a0da1ac.png)
Do you not see that in you browser? If not, please attach a screenshot and provide some details on your environment.

2) That is a good idea, but currently not an existing feature.

3) This is something I wanted to implement for a while now, so per your request I implemented a simple solution - the toggle state will now be stored in a cookie, so this actually means that if you collapse/hide the navbar, the next time you load a notebook (same or other) it will start that way. Please update to the latest version to see this change, and please report any bugs - this is fresh from just a few minutes ago and I didn't get to play around with it much.

**Comment by RabbitJackTrade** [comment]
>     1....   Do you not see that in you browser? If not, please attach a screenshot and provide some details on your environment.
I see it now! I guess I need more coffee...

>     2. That is a good idea, but currently not an existing feature.
The reason I was asking is that the readme states that
> The sidebar is resizable and **collapsible**.

so I assumed it refers to the hierarchy.

>     3. ...Please update to the latest version to see this change, and please report any bugs - this is fresh from just a few minutes ago and I didn't get to play around with it much.
Will be happy to do so and report back on any bugs, but just to make sure: by "update" you mean download it it again and rerun setup.py? No need to delete anything?

Again - thank you for your work, kind sir!

**Comment by shoval** [comment]
> I see it now! I guess I need more coffee...

Always a good idea :)

> so I assumed it refers to the hierarchy.

Sorry, I meant that the entire navbar "collapses" - meaning that you can close it. Perhaps it isn't phrased clearly enough. Microsoft uses this term for "collapsing the ribbon" in Office, so I assumed that would be familiar to people.

> download it it again and rerun setup.py?

Yep, that should do it.

Glad I could help!

**Comment by RabbitJackTrade** [comment]
Just a status update: updated to the recent version, been using it since we last chatted - and everything works great!
Thanks again.
